### ISSUE TITLE
Consider using the official Data Dragon CDN for champion images

### ISSUE THREAD

**Issue by Gnifle** [SubprimeLender/best_marksmen#1]
Hiya! Awesome project - gave me some very fitting results on my first try, and it seems everyone else is enjoying it as well.

A suggestion for your site: Instead of fetching champion images from your own champ_pic directory, consider looking into Riot Games' static data API (known as the _Data Dragon_) → https://developer.riotgames.com/docs/static-data. This allows you to get champion squares that:
- Are always up to date if you configure the URL to always get the latest version (for example: http://ddragon.leagueoflegends.com/cdn/6.8.1/img/champion/Aatrox.png - replace 6.8.1 with a method that fetches the latest CDN version)
- Reduces load on your own server

By the looks of it, I assume you've been aiming for some nostalgia by using every old champion square - but consider this suggestion a small challenge for yourself to implement. It could also lead to you learning a thing or two about using API's which is also useful if you end up trying to learn JS. The Riot Games API (https://developer.riotgames.com) is super well documented and simple to use once you get a hang of it :)

Let me know if you're completely stuck, and I can try and help you the best I can (I'm also learning myself)

**Comment by SubprimeLender** [comment]
That's brilliant! Thank you so much for the advice...I never knew that
existed. The server definitely needs some slack...

Respectfully,

On Sun, Apr 24, 2016 at 2:40 PM, Daniel Olsen notifications@github.com
wrote:

> Hiya! Awesome project - gave me some very fitting results on my first try,
> and it seems everyone else is enjoying it as well.
> 
> A suggestion for your site: Instead of fetching champion images from your
> own champ_pic directory, consider looking in to Riot Games' static data API
> (known as the _Data Dragon_) →
> https://developer.riotgames.com/docs/static-data. This allows you to get
> champion squares that:
> - Are always up to date if you configure the URL to always get the
>   latest version (for example:
>   http://ddragon.leagueoflegends.com/cdn/6.8.1/img/champion/Aatrox.png -
>   replace 6.8.1 with a method that fetches the latest CDN version)
> - Reduces load on your own server
> 
> By the looks of it, I assume you've been aiming for some nostalgia by
> using every old champion square - but consider this suggestion a small
> challenge for yourself to implement. It could also lead to you learning a
> thing or two about using API's which is also useful if you end up trying to
> learn JS. The Riot Games API (https://developer.riotgames.com) is super
> well documented and simple to use once you get a hang of it :)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/SubprimeLender/best_marksmen/issues/1

## 

_Tony Li_
Juris Doctor, May 2015
SMU Dedman School of Law

832-353-0722
tianyuel@smu.edu
li.tony98@gmail.com
